version: "3.7"
services:
  db:
    image: postgres:15
    container_name: db_app
    command: -p 5435
    expose:
      - 5435
    env_file:
      - .env

  app:
    build:
      context: .
    container_name: fastapi_app
    env_file:
      - .env
    command: ["/fastapi_app/docker/alembic_migrs.sh"]
    ports:
      - 9999:8000
    depends_on:
      - db

